# Generated by Django 5.0.1 on 2024-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('site', models.TextField(max_length=255)),
                ('quotation_date', models.DateField()),
                ('link_image', models.TextField(default='https://https://via.placeholder.com/150', max_length=500)),
            ],
        ),
    ]
